version: "3"
services:
  app:
    build: .
    links:
      - db
    ports:
      - "3000:3000"
    network_mode: host
  db:
    platform: linux/x86_64
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: canalservice
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro